build_ami:
  base_ami_product: com.ubuntu.cloud:server:16.04:amd64
  rootfs_skel_dirs:
    $append: rootfs.skel
  packages:
    $remove: docker.io
  commands:
    $extend:
      - "add-apt-repository --yes ppa:deadsnakes/ppa"
      - "apt-get update"
      - "apt-get install --yes python3.6-dev"
      - "pip install --upgrade pip virtualenv"
